platform :ios, '12.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'NamalReact' do
   # Stripe
   pod 'GoogleSignIn', '~> 6.0.2'
      pod 'AppAuth','~> 1.4.0'
# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
   # Install additional dependencies
  #  pod 'Firebase/Core'
  #  pod 'Firebase/Auth'
  # #  pod 'Firebase/Crash'
  #  pod 'Firebase/Database'
  #  pod 'Firebase/Firestore'
  #  pod 'Firebase/Messaging'
  #  pod 'Firebase/Performance'
  #  pod 'Firebase/Storage'
  # Pods for NamalReact
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'React-callinvoker', :path => "../node_modules/react-native/ReactCommon/callinvoker"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'


  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'


  pod 'RNRate', :path => '../node_modules/react-native-rate'


  pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'

 pod 'RCTRestart', :path => '../node_modules/react-native-restart/ios'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  target 'NamalReactTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end

target 'NamalReact-tvOS' do
  # Pods for NamalReact-tvOS

  target 'NamalReact-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
